import 'package:get/get.dart';
class RoutesHelper {
  static String initialScreen = "/";
  static String unknownScreen = "/";
  static String loginScreen = "/login";
  static String signUpScreen = "/sign-up";
  static String ForgotPasswordScreen = "/forgot_password";
  static String EmailVerificationScreen = "/email_verificatin";
  static String AccountVerificationSuccessful = "/account_verification_successful";
  static String HomePage = "/home_page";
  static String main_home_page = "/main_home_page";
  static String all_races_page = "/all_races_page";
  static String raceDetailsPage = "/race_details_page";
  static String successRegistration = "/successful_registration_page";
  static String paymentPage = "/payment_page";
  static String allRegistrationsPage = "/all_registrations_page";
  static String registrationDetailsPage = "/registration_details_page";
  static String allProductsScreen = "/all_products_screen";
  static String productDetailsScreen = "/product_details_screen";
  static String cartScreen = "/cart_screen";
  static String cartItemDetailsScreen = "/cart_item_details_screen";
  static String orderSuccessScreen = "/order_success_screen";
  static String allOrdersScreen = "/all_orders_screen";
  static String orderDetailScreen = "/order_detail_screen";
  static String newsDetailScreen = "/news_detail_screen";
  static String allNewsScreen = "/all_news_screen";
  static String createProfileScreen = "/create_profile_screen";
  static String profileScreen = "/profile_screen";
  static String viewCoachingCourseDetails = "/view_coaching_course_details";
  static String allCoachingCourseScreen = "/all_coaching_course_screen";
  static String coachingCourseBookingSuccess = "/coaching_course_booking_success";
  // static String paymentSuccessScreen = "/payment_success_screen";
}
